title: My Notepad
description: Some important notes during my learning of new technologies
theme: just-the-docs

url: https://raqib.me/my-notepad/

aux_links:
  Template Repository: https://github.com/omiq17/my-notepad
